[
{
'is_available': true,
'is_online': true,
'email': 'hi@deluvio.com',
'first_name': 'Charles',
'last_name': 'Deluvio',
'route': 'deluvio',
'bio': 'Charles Deluvio is a graphic designer from Montréal.',
'rate': '$60–100',
'links': [{'label':'Portfolio', 'url':'deluvio.com'}],
'skills': ['Branding', 'Design Thinking', 'UX', 'UI'],
'tags': ['designer']
},
{
'is_available': true,
'is_online': true,
'email': 'info@kirillz.com',
'first_name': 'Kirill',
'last_name': 'Zakharov',
'route': 'kirillz',
'bio': 'Kirill Zakharov is a Montreal-based product designer. Currently building Unsplash at Crew.',
'rate': '--',
'links': [{'label':'Portfolio', 'url':'kirillz.com'}],
'skills': ['Branding', 'Web Development', 'UI', 'UX'],
'tags': ['designer']
},
{
'is_available': true,
'is_online': true,
'email': 'pepinvanessa@gmail.com',
'first_name': 'Vanessa',
'last_name': 'Pépin',
'route': 'pepin',
'bio': 'Basée à Montréal, Vanessa Pépin offre ses services de direction artistique et de design graphique à la pige depuis 2013. Elle se spécialise en identité de marque, direction artistique, typographie et design web.',
'rate': '--',
'links': [{'label':'Portfolio', 'url':'pepinvanessa.com'}],
'skills': ['Branding', 'Art Direction', 'Web Design'],
'tags': ['designer']
},
{
'is_available': true,
'is_online': true,
'email': 'info@wedge.work',
'first_name': 'Justin',
'last_name': 'Lortie',
'route': 'lortie',
'bio': '',
'rate': '--',
'links': [{'label':'Portfolio', 'url':'wedge.work'}],
'skills': [''],
'tags': ['designer']
},
{
'is_available': true,
'is_online': true,
'email': 'snvilgrain@gmail.com',
'first_name': 'Sacha-Nicholas',
'last_name': 'Vilgrain',
'route': 'sachanicholas',
'bio': 'Sacha-Nicholas is a designer, illustrator, and woodworker. He has collaborated with a few startups, restaurants, and independent shops.',
'rate': '--',
'links': [{'label':'Portfolio', 'url':'sachanicholas.com'}],
'skills': [''],
'tags': ['designer', 'illustrator', 'maker']
},
{
'is_available': true,
'is_online': true,
'email': 'at@amelietourangeau.com',
'first_name': 'Amélie',
'last_name': 'Tourangeau',
'route': 'tourangeau',
'bio': 'Amélie Tourangeau is a freelance illustrator, designer & animation director based in Montréal.',
'rate': '--',
'links': [{'label':'Portfolio', 'url':'amelietourangeau.com/'}],
'skills': [''],
'tags': ['designer', 'illustrator', 'animator']
},
{
'is_available': true,
'is_online': true,
'email': 'me@oliverchank.com',
'first_name': 'Oliver',
'last_name': 'Chank',
'route': 'chank',
'bio': 'Oliver Chank is a graphic designer.',
'rate': '--',
'links': [{'label':'Portfolio', 'url':'oliverchank.com/'}],
'skills': ['Branding', 'Art Direction', 'UX', 'UI'],
'tags': ['designer']
},
{
'is_available': true,
'is_online': true,
'email': 'pao.iannucci@gmail.com',
'first_name': 'Paola',
'last_name': 'Iannu',
'route': 'paolaiannu',
'bio': '',
'rate': '--',
'links': [{'label':'Portfolio', 'url':'https://www.behance.net/paolaiannucci'}],
'skills': ['Branding', 'Art Direction', 'Photography'],
'tags': ['designer', 'photographer']
},
{
'is_available': true,
'is_online': true,
'email': 'hola@rodrigosergio.com',
'first_name': 'Rodrigo',
'last_name': 'Sergio',
'route': 'rodrigosergio',
'bio': 'Rodrigo is a Graphic designer / Art Director based in Montréal, Québec, Canada.',
'rate': '--',
'links': [{'label':'Portfolio', 'url':'rodrigosergio.com/'}],
'skills': ['Branding', 'Art Direction'],
'tags': ['designer']
},
{
'is_available': true,
'is_online': true,
'email': 'maxkaplun@gmail.com',
'first_name': 'Max',
'last_name': 'Kaplun',
'route': 'maxkaplun',
'bio': 'Max is an award-winning graphic designer with over 8 years experience in various interactive, arts, lifestyle and music brand-focused projects. Hailing from Brooklyn, he holds a graphic design degree from the School of Visual Arts. He's currently a Senior Art Director at Dynamo in Montreal, Canada.',
'rate': '--',
'links': [{'label':'Portfolio', 'url':'maxkaplun.com/'}],
'skills': ['Branding', 'Art Direction', 'Web Design', 'UI', 'UX'],
'tags': ['designer']
},
{
'is_available': true,
'is_online': true,
'email': 'hello@beckii.com',
'first_name': 'Bex',
'last_name': 'Adel',
'route': 'beckii',
'bio': 'Beckii is the creator of unique interfaces, intuitive user experiences, and custom iconography. Armed with an iterative process, a robust toolkit, and the flexibility to adapt to changing technologies and systems. She is currently working at Dynamo.',
'rate': '--',
'links': [{'label':'Portfolio', 'url':'beckii.com/'}],
'skills': ['UI', 'UX', 'Mobile Design'],
'tags': ['designer']
},
{
'is_available': true,
'is_online': true,
'email': 'bonjour@asaumierdemers.com ',
'first_name': 'Alexandre',
'last_name': 'Saumier Demers',
'route': 'asaumierdemers',
'bio': 'Type designer with a programming influence, a background in graphic design and a passion for cycling. Co-founder of Coppers & Brasses with Étienne Aubert Bonn, a type foundry established in Montréal. Recently graduated in graphic design at Université du Québec à Montréal and currently studying in Type and Media at The Royal Academy of Art, The Hague in The Netherlands.',
'rate': '--',
'links': [{'label':'Portfolio', 'url':'asaumierdemers.com/'}],
'skills': ['Type', 'Design', 'Sign Painting'],
'tags': ['designer', 'typographer']
},
{
'is_available': true,
'is_online': true,
'email': 'patricedidier@hotmail.com',
'first_name': 'Patrice',
'last_name': 'Didier',
'route': 'patricedidier',
'bio': '',
'rate': '--',
'links': [{'label':'Portfolio', 'url':'ruefullum.com/'}],
'skills': ['Branding', 'Art Direction', 'Packaging'],
'tags': ['designer']
},
{
'is_available': true,
'is_online': true,
'email': 'lian.benoit@gmail.com',
'first_name': 'Lian',
'last_name': 'Benoit',
'route': 'lianbenoit',
'bio': 'Hello! I likes to produce fun, unpredictable work that is supported by a clear underlying concept. I aim to rouse interest through design, coupling simplicity with an offbeat edge for a style that is cool and controlled. I enjoy experimenting with photography and illustration, integrating these elements with clean cut typography and layout.',
'rate': '--',
'links':[{'label':'Portfolio', 'url':'#'}],
'skills': [''],
'tags': ['']
},
{
'is_available': true,
'is_online': true,
'email': '',
'first_name': 'Charles',
'last_name': 'Fortier',
'route': '',
'bio': '',
'rate': '--',
'links':[{'label':'Portfolio', 'url':'#'}],
'skills': [''],
'tags': ['']
},
{
'is_available': true,
'is_online': true,
'email': '',
'first_name': 'Laurent',
'last_name': 'Laferrière',
'route': '',
'bio': '',
'rate': '--',
'links':[{'label':'Portfolio', 'url':'#'}],
'skills': [''],
'tags': ['']
},
{
'is_available': true,
'is_online': true,
'email': '',
'first_name': 'Alexandra',
'last_name': 'Nolot',
'route': '',
'bio': '',
'rate': '',
'links':[{'label':'Portfolio', 'url':'#'}],
'skills': [''],
'tags': ['']
},
{
'is_available': true,
'is_online': true,
'email': '',
'first_name': 'J.-S.',
'last_name': 'Chouinard',
'route': '',
'bio': '',
'rate': '',
'links':[{'label':'Portfolio', 'url':'#'}],
'skills': [''],
'tags': ['']
},
{
'is_available': true,
'is_online': true,
'email': '',
'first_name': 'Gabrielle',
'last_name': 'Madé',
'route': '',
'bio': '',
'rate': '',
'links':[{'label':'Portfolio', 'url':'#'}],
'skills': [''],
'tags': ['']
},
{
'is_available': true,
'is_online': true,
'email': 'hoso.tran@me.com',
'first_name': 'Hoang-Son',
'last_name': 'Tran',
'route': 'hoangsontran',
'bio': 'Allô, mon nom est Hoang‑Son et je suis un designer graphique de Montréal.',
'rate': '--',
'links': [{'label':'Portfolio', 'url':'hoangsontran.com/'}],
'skills': [''],
'tags': ['']
},
{
'is_available': true,
'is_online': true,
'email': '',
'first_name': 'Philippe',
'last_name': 'Gauthier',
'route': 'philippegauthier',
'bio': 'Associate Design Director at Character. ',
'rate': '--',
'links': [{'label':'Portfolio', 'url':'https://dribbble.com/philgauthier'}],
'skills': [''],
'tags': ['']
},
{
'is_available': true,
'is_online': true,
'email': '',
'first_name': 'Camille',
'last_name': 'Miron-Sauvé',
'route': 'camillemironsauve',
'bio': '',
'rate': '',
'links':[{'label':'Portfolio', 'url':'#'}],
'skills': [''],
'tags': ['']
},
{
'is_available': true,
'is_online': true,
'email': '',
'first_name': 'Edith',
'last_name': 'Morin',
'route': 'edithmorin',
'bio': '',
'rate': '',
'links':[{'label':'Portfolio', 'url':'#'}],
'skills': [''],
'tags': ['']
},
{
'is_available': true,
'is_online': true,
'email': '',
'first_name': 'Kevin',
'last_name': 'Clark',
'route': 'kevinclark',
'bio': '',
'rate': '',
'links':[{'label':'Portfolio', 'url':'#'}],
'skills': [''],
'tags': ['']
}
]